### ISSUE TITLE
FYI: Washington Hospital version of improvised PAPR

### ISSUE THREAD

**Issue by chonghorizons** [jcl5m1/ventilator#110]
I'm trying to get a hold of you about your PAPR designs. Specifically, I'm organizing a group of (loosely vetted) people who are seriously working on improvised PPE. 

**Halo design video, and 3-d print files**
Specifically, these doctors/HCP solved a lot of the PPR issues:  https://www.youtube.com/watch?v=JMXP8jAmDKA&feature=youtu.be

Innovations:  existing inline viral filters (widely available in hospitals) and use of disposable plastic bag for hood.

I'm hocho on this discord server: https://discord.gg/H3jUmar  (all welcome, and expect to be vetted lightly)
or chongare@gmail.com or 607-279-3623 (text/phone)

In it to make an impact and move the needle. Working 12hr days 7 days a week. Mainly, i'm organizing and connecting people.

**Comment by chonghorizons** [comment]
Here is a picture.
![Screenshot 2020-04-11 at 8 47 20 AM](https://user-images.githubusercontent.com/36284839/79044080-29ecfd80-7bd1-11ea-9a45-0b566203423e.png)

**Comment by StevenACoffman** [comment]
Have you seen this open source design: https://making.engr.wisc.edu/papr/

**Comment by chonghorizons** [comment]
Yeah. The madison badger design is great. It is on the more complex and expensive side.

[Http://BunnyPAPR.org] is streamlined down to a production cost of under $30. 

I actually have it under $10 now by cutting out the 3D parts.
