### ISSUE TITLE
CAD Interoperability Formats

### ISSUE THREAD

**Issue by axjjienn** [jcl5m1/ventilator#12]
I wanted to know if we can include some non-tessellated (Parasolid, Step, ACIS) CAD formats for the files so that people coming into the project don't have to remodel based on an STL master. I think this would help everyone get moving on the project, and speed up cooperation.

I recommend Parasolid, as it is the native format for many CAD systems, including Inventor, SolidWorks, and NX to name a few.

If this is not possible, I would recommend STEP files, as they are the international standard for CAD Interoperability, as codified in ISO 10303-21.

**Comment by jcl5m1** [comment]
Thanks for the recommendation.  I added the links to the Fusion 360 web viewer, which allows exporting to STEP and other formats.
