### ISSUE TITLE
Offering help with the TO-DOs

### ISSUE THREAD

**Issue by MostafaAbdelmegeed** [jcl5m1/ventilator#50]
Hello Johnny,

Very inspiring what you are doing, myself and a team of Biomedical Engineering Senior year Students would like to help with the TO-DOs, we have a pretty good background with both the Medical and the Engineering aspects of the electro-mechanical ventilation systems and would gladly invest our times in such project.

Email me if possible at mostafa0as3d@gmail.com

**Comment by jcl5m1** [comment]
HI Mustafa,

Feel free to choose a to do, and reply to an existing issue, or create a
relevant one.

It will be easier to track work on github than via email.

-johnny
