### ISSUE TITLE
Use Decathlon or similar diving mask as C-PAP mask

### ISSUE THREAD

**Issue by PaulStefaan** [jcl5m1/ventilator#69]
Hi, 

In Europ, we have a project to mod a diving mask to a C-PAP mask 
--- It's tested and in use now in Italy ---

See link 
https://www.isinnova.it/easy-covid19-eng/

Video
[https://youtu.be/w4Csqdxkrfw](url)

![photo](https://user-images.githubusercontent.com/43759151/77519985-c351ab00-6e80-11ea-994b-5c43bb9c3059.jpg)

By https://www.isinnova.it/

**Comment by DaveM135** [comment]
Very interested in this.   I’m in the SF Bay Area.   I am a pulmonologist.   Can you put me in touch with anyone who is using it in Italy?

Best

Dave

**Comment by PaulStefaan** [comment]
> Very interested in this. I’m in the SF Bay Area. I am a pulmonologist. Can you put me in touch with anyone who is using it in Italy? Best Dave
> […](#)
> On Mar 25, 2020, at 02:09, Paul Stefaan Mooij ***@***.***> wrote: ﻿ Hi, In Europ, we have a project to mod a diving mask to a C-PAP mask See link https://www.isinnova.it/easy-covid19-eng/ Video https://youtu.be/w4Csqdxkrfw By https://www.isinnova.it/ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi Dave,

Nice to meet you ( I'm located in  Amsterdam)  

Here contact info 
 "the Chiari Hospital"
Dr Fracassi and Mr Romaioli

Article: 
https://www.foxnews.com/world/coronavirus-italy-ventilator-valve-supply-business

![ET2wDx7X0AEDXay](https://user-images.githubusercontent.com/43759151/77583914-2aec1280-6ee2-11ea-9e63-9ca4ea36ffb3.jpeg)
