### ISSUE TITLE
Jupyter notebook for visualize.py

### ISSUE THREAD

**Issue by mxochicale** [jcl5m1/ventilator#72]
HI @jcl5m1 

I see that you are already have [ventilator_data_analysis.ipynb](https://colab.research.google.com/drive/1iFMmMMrg_3OeifzJikT75fy4ev84W235) But perhaps, to keep track of changes in the same repository of [`visualize.py`](https://github.com/jcl5m1/ventilator/blob/master/data_analysis/visualize.py), a Jupyter notebook might be helpful.  Will later put a PR for that :-)

**Comment by peteflorence** [comment]
Agreed would be helpful to track code changes, if you PR a working notebook I can merge it
