### ISSUE TITLE
Helping out with Todos

### ISSUE THREAD

**Issue by kenryhou2** [jcl5m1/ventilator#81]
Hi @jcl5m1  @nasocializes , I'm an EE undergrad at UCLA, with some knowledge of PCB design, matlab, python, and programming arduinos. I was looking over your documentation, and would like to help out with some of the to dos. Having limited resources and no med background, I'm not sure if I can recreate and test aspects of your todos in ways useful. But I'm available if you'd like to offload any busy work in modeling and design especially with electronics, because I'd like to make this as easy for you as possible. Any chance we could briefly talk through github or email (kouhenry@yahoo.com) would be awesome. Thanks in advance and great work.

**Comment by nasocializes** [comment]
Thanks for volunteering. Feel free to pick a ToDo if there's any there that you feel you can help with. I hope you and your family are well!
https://github.com/jcl5m1/ventilator#to-dos-aka-things-i-could-use-help-with
