### ISSUE TITLE
Medtronic open sourced all of their PB560 ventilator files

### ISSUE THREAD

**Issue by qsullivan11** [jcl5m1/ventilator#92]
See [Medtronic's site ](https://www.medtronic.com/us-en/e/open-files.html?cmpid=vanity_url_medtronic_com_openventilator_Corp_US_Covid19_FY20)to download. 
There's manufacturing documents, manuals, electrical schematics, most everything.

**Comment by jcrubino** [comment]
[PB560 Users Manual](http://www.amg.com.tr/uploads/files/PB560_UsersManual_EN_10066883B00.pdf)

**Comment by qsullivan11** [comment]
done
